"""Simple Execution Engine — Backtrader/Zipline pattern.

Clean execution flow:
Signal → Order → Execution → Position

Rules:
- Fills orders at NEXT BAR OPEN
- Handles SL/TP using OHLC (high/low, NOT close)
- Position stores state only (no logic)
- PnL calculated externally
"""

from typing import Dict, List, Optional, Tuple
from datetime import datetime
from dataclasses import dataclass

from .order import Order, OrderSide, OrderStatus
from ..portfolio.position import Position


@dataclass
class OHLC:
    """OHLC bar data."""
    open: float
    high: float
    low: float
    close: float
    timestamp: datetime


class SimpleExecutionEngine:
    """
    Simple execution engine — fills orders using OHLC data.
    
    Flow:
    1. Signal generated by strategy
    2. Signal converted to Order
    3. Order filled at next bar OPEN
    4. Position created from filled order
    5. SL/TP checked using OHLC (high/low)
    """
    
    def __init__(self):
        """Initialize execution engine."""
        self.pending_orders: List[Order] = []
        self.positions: Dict[str, Position] = {}  # symbol -> Position
        self.closed_positions: List[Position] = []
    
    def place_order(self, order: Order) -> None:
        """Place an order (adds to pending queue)."""
        self.pending_orders.append(order)
    
    def process_bar(self, symbol: str, ohlc: OHLC) -> List[Tuple[Position, str, float]]:
        """
        Process one OHLC bar.
        
        Returns list of (position, exit_reason, exit_price) for closed trades.
        """
        closed_trades = []
        
        # 1. Fill pending orders at bar open
        self._fill_pending_orders(symbol, ohlc)
        
        # 2. Check SL/TP for open positions using OHLC
        if symbol in self.positions:
            pos = self.positions[symbol]
            if pos.is_open:
                exit_info = self._check_exit_conditions(pos, ohlc)
                if exit_info:
                    exit_reason, exit_price = exit_info
                    # Close position
                    pos.close(exit_price, exit_reason)
                    closed_trades.append((pos, exit_reason, exit_price))
                    
                    # Move to closed list
                    self.closed_positions.append(pos)
                    del self.positions[symbol]
        
        return closed_trades
    
    def _fill_pending_orders(self, symbol: str, ohlc: OHLC) -> None:
        """Fill pending orders at bar open price."""
        remaining_orders = []
        
        for order in self.pending_orders:
            if order.symbol != symbol:
                remaining_orders.append(order)
                continue
            
            if not order.is_pending:
                remaining_orders.append(order)
                continue
            
            # Market order fills at open price
            fill_price = ohlc.open
            order.mark_filled(fill_price, ohlc.timestamp)
            
            # Create position from filled order
            if order.is_long:
                # Buy order creates LONG position (positive quantity)
                quantity = abs(order.size)
            else:
                # Sell order creates SHORT position (negative quantity)
                quantity = -abs(order.size)
            
            # Close existing position if reversing
            if symbol in self.positions:
                existing_pos = self.positions[symbol]
                if (existing_pos.quantity > 0 and quantity < 0) or \
                   (existing_pos.quantity < 0 and quantity > 0):
                    # Reverse position — close existing first
                    existing_pos.close(fill_price, "reverse")
                    self.closed_positions.append(existing_pos)
            
            # Create new position
            position = Position(
                symbol=symbol,
                entry_price=fill_price,
                quantity=quantity,
                current_price=fill_price
            )
            
            self.positions[symbol] = position
        
        self.pending_orders = remaining_orders
    
    def _check_exit_conditions(self, pos: Position, ohlc: OHLC) -> Optional[Tuple[str, float]]:
        """
        Check if position should exit based on OHLC.
        
        LONG:
        - SL: if low <= stop_loss → exit at stop_loss
        - TP: if high >= take_profit → exit at take_profit
        
        SHORT:
        - SL: if high >= stop_loss → exit at stop_loss
        - TP: if low <= take_profit → exit at take_profit
        
        Returns (exit_reason, exit_price) or None.
        """
        if not pos.is_open:
            return None
        
        # LONG position
        if pos.quantity > 0:
            # Check stop loss
            if pos.stop_loss is not None and ohlc.low <= pos.stop_loss:
                return ("stop_loss", pos.stop_loss)
            # Check take profit
            if pos.take_profit is not None and ohlc.high >= pos.take_profit:
                return ("take_profit", pos.take_profit)
        
        # SHORT position
        elif pos.quantity < 0:
            # Check stop loss
            if pos.stop_loss is not None and ohlc.high >= pos.stop_loss:
                return ("stop_loss", pos.stop_loss)
            # Check take profit
            if pos.take_profit is not None and ohlc.low <= pos.take_profit:
                return ("take_profit", pos.take_profit)
        
        return None
    
    def set_stop_loss(self, symbol: str, stop_loss: float) -> None:
        """Set stop loss for position."""
        if symbol in self.positions:
            self.positions[symbol].stop_loss = stop_loss
    
    def set_take_profit(self, symbol: str, take_profit: float) -> None:
        """Set take profit for position."""
        if symbol in self.positions:
                self.positions[symbol].take_profit = take_profit
    
    def get_position(self, symbol: str) -> Optional[Position]:
        """Get open position for symbol."""
        return self.positions.get(symbol)
    
    def get_all_positions(self) -> List[Position]:
        """Get all open positions."""
        return list(self.positions.values())
    
    def close_position(self, symbol: str, price: float, reason: str) -> Optional[float]:
        """Manually close position."""
        if symbol in self.positions:
            pos = self.positions[symbol]
            pnl = pos.close(price, reason)
            self.closed_positions.append(pos)
            del self.positions[symbol]
            return pnl
        return None
